### PR TITLE
Change visibility of some Fixer properties into private

### PR DESCRIPTION
**Pull request by AmraniCh**
## CHANGES

* Convert visibility of properties (`protectedTags`, `locale`, `_rules`, `stateBag`) from protected into private.
* Added getter for `protectedTags` property.

## NOTES

* For the `stateBag` property I didn't add a getter for it because it is used only in a private part of the fixer class, if a user needs an instance of the `StateBag` class, he can have his own property in his derived class.

### CODE REVIEW

**Review by lyrixx — APPROVED** [review]
LGTM

**Comment by AmraniCh** [comment]
Since the properties are now private and no longer part of the public API I added the type declarations also (#84).

**Comment by AmraniCh** [comment]
@damienalexandre what do you think?

**Comment by damienalexandre** [comment]
Perfect :+1: thanks a lot

**Pull request merged**
